### ISSUE TITLE
Issues with the readme

### ISSUE THREAD

**Issue by rzarai** [abletsoff/joplin-anki-sync#1]
The readme is poorly written.  
What this token.json file is for? Where do I put it?  
Where do I get this id string from?  
The instruction literally tells just "create a file", put something I don't know where it is in there, and then proceeds showing the demo.  
I'd be better if the creator will clarify.

**Comment by rzarai** [comment]
Also the demo launches joplin-anki-sync script. Do I clone the repository for it? Or there is a separate program? Is it available on AUR, for example? Please clarify this as well.

**Comment by abletsoff** [comment]
The README.md has been updated.
